### ISSUE TITLE
no post event

### ISSUE THREAD

**Issue by electromuis** [helios-ag/ElFinderPHP#37]
I want to listen if any scss files are uploaded (to compile them), but the post event is not being fired or captured. 
Pre works fine tough

    public function onPostExecute()
    {
        //mkdir(312);
    }

    public function onPreExecute()
    {
        //mkdir(123);
    }

  data_bundle.product_theme_manager:
    class: Verhuurnet\DataBundle\ProductThemeManager
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      -  { name: fm_elfinder.event_listener, event: fm_elfinder.event.post_execution, method: onPostExecute }
      -  { name: fm_elfinder.event_listener, event: fm_elfinder.event.pre_execution, method: onPreExecute }

**Comment by nicolasmure** [comment]
wow weird, do you have any web browser's console output to attach here?
It looks like there is an error happening during the upload process.

**Comment by nicolasmure** [comment]
Have you st the `cors_support` key to `true` in your config file? (as specified [in the doc](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/doc/events-listeners-subscribers.md#events))

**Comment by electromuis** [comment]
The browser doesnt output anything special, works as expected.
And i saw that i needed to enable that option, but it didnt specify where. Since the pre does work i tought it was OK.
If i put it in config it doesn't recornise it

fm_elfinder:
    cors_support: true
    instances:
        themes:
        .......

Unrecognized option "cors_support" under "fm_elfinder"

And in parameters is doesn't change the outcome

parameters:
    cors_support: true
    ......

**Comment by nicolasmure** [comment]
Yeah, actually, the elFinder PHP library used to call php's `exit` function when it has finished to handle the request. So the symfony full life cycle couldn't be performed because of this hard exit.

Thats why the pre exec event is triggered, and not the post exec event because PHP stops and the end of the elFinder lib execution.

By setting the `cors_support` option to `true` ([go here to know how](https://github.com/helios-ag/FMElfinderBundle/blob/master/Resources/doc/cors-support.md "CORS support doc")), the `exit` call is no more performed by the lib and the SF lifecycle can continue, and the post exec event is triggered.

**Comment by nicolasmure** [comment]
If you're not using elFinder across different domain names, you won't need the NelmioCORSBundle at it says it the doc, just set the `cors_support` config key to `true` to avoid the hard `exit` from the elFinder library.

**Comment by electromuis** [comment]
That fixed it, thank you!
